name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./BlazorApp/BlazorApp.csproj

      - name: Build the app
        run: dotnet build --configuration Release ./BlazorApp/BlazorApp.csproj

      - name: Publish the app
        run: dotnet publish --configuration Release --output ./publish ./BlazorApp/BlazorApp.csproj

      - name: Build Docker image
        run: docker build -t myblazorapp:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag myblazorapp:latest bertontheone/myblazorapp:latest

      - name: Push Docker image to Docker Hub
        run: docker push bertontheone/myblazorapp:latest

