name: Mover Tarea a Columna Específica en Proyecto de Usuario

on:
  push:
    branches:
      - main

jobs:
  move_task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mover tarea al hacer commit
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const taskRegex = /#(\d+)/; // Regex para identificar el número de tarea
            const commitMessage = github.context.payload.commits[0].message;
            const taskNumberMatch = commitMessage.match(taskRegex);

            if (taskNumberMatch) {
              const taskNumber = taskNumberMatch[1];
              const projectName = 'Super proyecto'; // Reemplaza con el nombre de tu proyecto
              const columnName = 'In review'; // Reemplaza con el nombre de la columna deseada

              // Consulta GraphQL para obtener el ID del proyecto
              const projectIdQuery = `
                query ($login: String!, $projectName: String!) {
                  user(login: $login) {
                    projectNext(number: 2) {
                      id
                    }
                  }
                }
              `;

              // Ejecutar la consulta GraphQL para obtener el ID del proyecto
              const projectIdResponse = await github.graphql(projectIdQuery, {
                login: github.context.repo.owner,
                projectName: projectName
              });

              const projectId = projectIdResponse.user.projectNext.id;

              // Consulta GraphQL para mover la tarea
              const moveTaskMutation = `
                mutation ($projectId: ID!, $taskNumber: Int!, $columnName: String!) {
                  updateProjectNextItemField(input: {
                    projectId: $projectId,
                    itemId: $taskNumber,
                    fieldId: "status", # 'status' es el ID de las columnas en el proyecto
                    value: $columnName
                  }) {
                    projectNextItem {
                      id
                    }
                  }
                }
              `;

              // Ejecutar la mutación GraphQL para mover la tarea
              await github.graphql(moveTaskMutation, {
                projectId: projectId,
                taskNumber: parseInt(taskNumber),
                columnName: columnName
              });
            }
