name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Usar la rama master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Setup SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
     - name: Add SSH Known Hosts
       run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
            
     - name: ls -a via ssh
       uses: garygrossgarten/github-action-ssh@release
       with:
        command: ls -a
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
        
     - name: Deploy to Local Server
       uses: appleboy/ssh-action@v1.0.3
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       with:
         host: ${{ secrets.SSH_HOST }}
         port: ${{ secrets.SSH_PORT }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         envs: DOCKER_USERNAME, DOCKER_PASSWORD
         script: |
           powershell -Command "
           echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin;
           docker pull $DOCKER_USERNAME/myblazorapp:latest;
           docker image prune -f;
           if (docker ps -q -f name=myblazorapp_container) {
             docker stop myblazorapp_container;
             docker rm myblazorapp_container;
           }
           docker run -d -p 8080:80 --name myblazorapp_container $DOCKER_USERNAME/myblazorapp:latest;"
