name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Usar la rama master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Setup SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
     - name: Add SSH Known Hosts
       run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
            
     - name: Deploy visa SSH
       uses: D3rHase/ssh-command-action@v0.2.2
       with:
        host: ${{secrets.SSH_HOST}} # Remote server address / ip - required
        port: ${{secrets.SSH_PORT}} # Remote server port -  Default: 22 - optional
        user: ${{secrets.SSH_USERNAME}} # Remote server user - required
        private_key: ${{secrets.SSH_PRIVATE_KEY}} # Private ssh key registered on the remote server - required
        command: |
          # Iniciar sesión en Docker
          echo "Logging in to Docker..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          if ($LASTEXITCODE -ne 0) {
            Handle-Error "Docker login failed."
          }
        
