name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Usar la rama master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Setup SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
     - name: Add SSH Known Hosts
       run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
            
     - name: Deploy to Local Server
       uses: JimCronqvist/action-ssh@master
       env:
          NAME: "Root"
       with:
          hosts: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: false
          shell: pwsh
          command: |
            ls -lah
            echo "I am $NAME"
