name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Usar la rama master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Setup SSH
       uses: webfactory/ssh-agent@v0.5.3
       with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
     - name: Add SSH Known Hosts
       run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        
     - name: Deploy to Local Server
       uses: appleboy/ssh-action@v1.0.3
       env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Avoid hardcoding in script
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Optional, use token if available
       with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKER_USERNAME, DOCKER_PASSWORD
          script: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker pull "$DOCKER_USERNAME"/myblazorapp:latest
